//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI4E.Storage.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI4E.Storage.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be a delegate..
        /// </summary>
        internal static string ArgumentMustNotBeADelegate {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeADelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not be a value-type..
        /// </summary>
        internal static string ArgumentMustNotBeAValueType {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeAValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not specify a delegate type..
        /// </summary>
        internal static string ArgumentMustNotSpecifyDelegateType {
            get {
                return ResourceManager.GetString("ArgumentMustNotSpecifyDelegateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not specify an interface-type..
        /// </summary>
        internal static string ArgumentMustNotSpecifyInterfaceType {
            get {
                return ResourceManager.GetString("ArgumentMustNotSpecifyInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not specify an open generic type definition..
        /// </summary>
        internal static string ArgumentMustNotSpecifyOpenTypeDefinition {
            get {
                return ResourceManager.GetString("ArgumentMustNotSpecifyOpenTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not specify a value-type..
        /// </summary>
        internal static string ArgumentMustNotSpecifyValueType {
            get {
                return ResourceManager.GetString("ArgumentMustNotSpecifyValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing all changes to the domain storage. Scope {0}.
        /// </summary>
        internal static string Committing {
            get {
                return ResourceManager.GetString("Committing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the entity with identifier {0} from the storage engine. Scope {1}.
        /// </summary>
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatching domain-event of type {0}. Scope: {1}.
        /// </summary>
        internal static string DispatchingDomainEvent {
            get {
                return ResourceManager.GetString("DispatchingDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for concurrent changes on entity with identifier {0}. Scope: {1}.
        /// </summary>
        internal static string EngineCheckingConcurrency {
            get {
                return ResourceManager.GetString("EngineCheckingConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused to further the process commit attempt as the concurrency check failed. Scope: {0}.
        /// </summary>
        internal static string EngineCommitAttemptConcurrencyCheckFailed {
            get {
                return ResourceManager.GetString("EngineCommitAttemptConcurrencyCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully commit attempt. Scope: {0}.
        /// </summary>
        internal static string EngineCommitSuccess {
            get {
                return ResourceManager.GetString("EngineCommitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency check on entity with identifier {0} failed. Scope: {1}.
        /// </summary>
        internal static string EngineConcurrencyCheckFailed {
            get {
                return ResourceManager.GetString("EngineConcurrencyCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency check on entity with identifier {0} failed. Updating cache. Scope: {1}.
        /// </summary>
        internal static string EngineConcurrencyCheckFailedUpdatingCache {
            get {
                return ResourceManager.GetString("EngineConcurrencyCheckFailedUpdatingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting entity with identifier {0} in the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineDeletetingEntityFromDatabase {
            get {
                return ResourceManager.GetString("EngineDeletetingEntityFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the domain-event batch of the entity with the identifier {0} and the marked as deleted entity from the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineDeletingDomainEventBatchAndEntityFromDatabase {
            get {
                return ResourceManager.GetString("EngineDeletingDomainEventBatchAndEntityFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the domain-event batch of the entity with the identifier {0} from the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineDeletingDomainEventBatchFromDatabase {
            get {
                return ResourceManager.GetString("EngineDeletingDomainEventBatchFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain-event batch of entity with identifer {0} dispatched successfully. Scope: {1}.
        /// </summary>
        internal static string EngineDispatchedDomainEventBatch {
            get {
                return ResourceManager.GetString("EngineDispatchedDomainEventBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering domain-event batch of entity with identifer {0} for dispatch. Scope: {1}.
        /// </summary>
        internal static string EngineDispatchingDomainEventBatch {
            get {
                return ResourceManager.GetString("EngineDispatchingDomainEventBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering all domain-event batched for dispatch. Scope: {1}.
        /// </summary>
        internal static string EngineDispatchingMultipleDomainEventBatches {
            get {
                return ResourceManager.GetString("EngineDispatchingMultipleDomainEventBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to commit the transaction to the underlying database due to concurrency issues. Restarting the transaction. Scope: {0}.
        /// </summary>
        internal static string EngineFailedToCommitTransaction {
            get {
                return ResourceManager.GetString("EngineFailedToCommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading entity with identifier {0} from underlying database for reason: &apos;{1}&apos;. Scope: {2}.
        /// </summary>
        internal static string EngineFailureLoadingEntityFromDatabase {
            get {
                return ResourceManager.GetString("EngineFailureLoadingEntityFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized the domain storage engine. Scope: {1}.
        /// </summary>
        internal static string EngineInitialized {
            get {
                return ResourceManager.GetString("EngineInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the domain storage engine. Scope: {1}.
        /// </summary>
        internal static string EngineInitializing {
            get {
                return ResourceManager.GetString("EngineInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded and processed entities of type {0} from the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineLoadedEntitiesFromDatabase {
            get {
                return ResourceManager.GetString("EngineLoadedEntitiesFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded entity with identifier {0} from the underyling database. Scope: {1}.
        /// </summary>
        internal static string EngineLoadedEntityFromDatabase {
            get {
                return ResourceManager.GetString("EngineLoadedEntityFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity with default identity from the underlying database results in failure loading-result. Scope: {0}.
        /// </summary>
        internal static string EngineLoadingDefaultEntityIdentifier {
            get {
                return ResourceManager.GetString("EngineLoadingDefaultEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entities of type {0} from the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineLoadingEntitiesFromDatabase {
            get {
                return ResourceManager.GetString("EngineLoadingEntitiesFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity with identifier {0} in from cache. Scope: {1}.
        /// </summary>
        internal static string EngineLoadingEntityFromCache {
            get {
                return ResourceManager.GetString("EngineLoadingEntityFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity with identifier {0} in from the underyling database. Scope: {1}.
        /// </summary>
        internal static string EngineLoadingEntityFromDatabase {
            get {
                return ResourceManager.GetString("EngineLoadingEntityFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking the domain-event batch of entity with identifier {0} as dispatched. Scope: {1}.
        /// </summary>
        internal static string EngineMarkingDomainEventBatchAsDispatched {
            get {
                return ResourceManager.GetString("EngineMarkingDomainEventBatchAsDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing commit attempt. Scope: {0}.
        /// </summary>
        internal static string EngineProcessingCommitAttempt {
            get {
                return ResourceManager.GetString("EngineProcessingCommitAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing loaded entity with identifier {0}. Scope: {1}.
        /// </summary>
        internal static string EngineProcessingEntity {
            get {
                return ResourceManager.GetString("EngineProcessingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency check for commit attempt succeeded. Started database transaction. Scope: {0}.
        /// </summary>
        internal static string EngineStartedCommitTransaction {
            get {
                return ResourceManager.GetString("EngineStartedCommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing store operation to the underlying database marking the entity with identifer {0} as deleted. Scope: {1}.
        /// </summary>
        internal static string EngineStoringEntityMarkedAsDeletedToDatabase {
            get {
                return ResourceManager.GetString("EngineStoringEntityMarkedAsDeletedToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing entity with identifier {0} in the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineStoringEntityToDatabase {
            get {
                return ResourceManager.GetString("EngineStoringEntityToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing domain-event batch of entity with identifier {0} to the underlying database. Scope: {1}.
        /// </summary>
        internal static string EngineWritingDomainEventBatchToDatabase {
            get {
                return ResourceManager.GetString("EngineWritingDomainEventBatchToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified load result must indicate success..
        /// </summary>
        internal static string EntityLoadResultMustIndicateSuccess {
            get {
                return ResourceManager.GetString("EntityLoadResultMustIndicateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity must be assignable to the specified entity-type..
        /// </summary>
        internal static string EntityMustBeAsignableToEntityType {
            get {
                return ResourceManager.GetString("EntityMustBeAsignableToEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified entity must be assignable to the specified entity type..
        /// </summary>
        internal static string EntityMustBeAssignableToEntityType {
            get {
                return ResourceManager.GetString("EntityMustBeAssignableToEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event is not assignable to the specified event type..
        /// </summary>
        internal static string EventMustBeAssignableToEventType {
            get {
                return ResourceManager.GetString("EventMustBeAssignableToEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown on dispatching domain-event of type {0}. Scope: {1}.
        /// </summary>
        internal static string ExceptionDispatchingDomainEvent {
            get {
                return ResourceManager.GetString("ExceptionDispatchingDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to dispatch domain-event of type {0} for reason: &apos;{1}&apos;. Scope: {2}.
        /// </summary>
        internal static string FailureDispatchingDomainEvent {
            get {
                return ResourceManager.GetString("FailureDispatchingDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading entity with identifier {0} for reason: &apos;{1}&apos;. Scope: {2}.
        /// </summary>
        internal static string FailureLoadingEntity {
            get {
                return ResourceManager.GetString("FailureLoadingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking query-executor for entity with identifier {0}. Scope {1}.
        /// </summary>
        internal static string InvokingQueryExecutor {
            get {
                return ResourceManager.GetString("InvokingQueryExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded and processed entities of type {0} from the underlying storage-engine. Scope: {1}.
        /// </summary>
        internal static string LoadedEntities {
            get {
                return ResourceManager.GetString("LoadedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded entity with identifier {0}. Scope: {1}.
        /// </summary>
        internal static string LoadedEntity {
            get {
                return ResourceManager.GetString("LoadedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity with default identity from th eunderlying storage engine resulted in failure loading-result. Scope: {0}.
        /// </summary>
        internal static string LoadingDefaultEntityIdentifier {
            get {
                return ResourceManager.GetString("LoadingDefaultEntityIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entities of type {0} from the underlying storage-engine. Scope: {1}.
        /// </summary>
        internal static string LoadingEntities {
            get {
                return ResourceManager.GetString("LoadingEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [None].
        /// </summary>
        internal static string NoScope {
            get {
                return ResourceManager.GetString("NoScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity cannot be found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity does not match the expected concurrency token..
        /// </summary>
        internal static string NotMatchedExpectedConcurrencyToken {
            get {
                return ResourceManager.GetString("NotMatchedExpectedConcurrencyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity does not match the expected range of revision..
        /// </summary>
        internal static string NotMatchedExpectedRevision {
            get {
                return ResourceManager.GetString("NotMatchedExpectedRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing loaded entity with identifier {0}. Scope: {1}.
        /// </summary>
        internal static string ProcessingEntity {
            get {
                return ResourceManager.GetString("ProcessingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executor failed loading entity with identifier {0} for reason: &apos;{1}&apos;. Scope: {2}.
        /// </summary>
        internal static string QueryExecutorFailureLoadingEntity {
            get {
                return ResourceManager.GetString("QueryExecutorFailureLoadingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executor loaded entity with identifier {0}. Scope: {1}.
        /// </summary>
        internal static string QueryExecutorLoadedEntity {
            get {
                return ResourceManager.GetString("QueryExecutorLoadedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executor is loading entity with identifier {0} from the underlying storage engine. Scope {1}.
        /// </summary>
        internal static string QueryExecutorLoadingEntityFromStorageEngine {
            get {
                return ResourceManager.GetString("QueryExecutorLoadingEntityFromStorageEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query executor is loading entity with identifier {0} from the unit of work. Scope {1}.
        /// </summary>
        internal static string QueryExecutorLoadingEntityFromUnitOfWork {
            get {
                return ResourceManager.GetString("QueryExecutorLoadingEntityFromUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested entity with identifier {0}. Invoking query processor {1}. Scope: {1}.
        /// </summary>
        internal static string RequestedEntity {
            get {
                return ResourceManager.GetString("RequestedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling back all changes to the domain storage. Scope {0}.
        /// </summary>
        internal static string RollingBack {
            get {
                return ResourceManager.GetString("RollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing the entity with identifier {0} to the storage engine. Scope {1}.
        /// </summary>
        internal static string Storing {
            get {
                return ResourceManager.GetString("Storing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully dispatched domain-event of type {0}. Scope: {1}.
        /// </summary>
        internal static string SuccessfullyDispatchedDomainEvent {
            get {
                return ResourceManager.GetString("SuccessfullyDispatchedDomainEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity was loaded successfully..
        /// </summary>
        internal static string SuccessfullyLoaded {
            get {
                return ResourceManager.GetString("SuccessfullyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must not indicate a negative time-span..
        /// </summary>
        internal static string TimeSpanMustNotBeNegative {
            get {
                return ResourceManager.GetString("TimeSpanMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified tracked-entity must not be in state {0}..
        /// </summary>
        internal static string TrackedEntityMustNotBeInState {
            get {
                return ResourceManager.GetString("TrackedEntityMustNotBeInState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown reason.
        /// </summary>
        internal static string UnknownReason {
            get {
                return ResourceManager.GetString("UnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced or updated the processed entity with identifier {0} in the unit of work. Scope {1}.
        /// </summary>
        internal static string UpdatedTrackedEntityInUnitOfWork {
            get {
                return ResourceManager.GetString("UpdatedTrackedEntityInUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced the processed entity with identifier {0} in the unit of work. Skipping entity. Scope {1}.
        /// </summary>
        internal static string UpdatedTrackedEntityInUnitOfWorkNonExisting {
            get {
                return ResourceManager.GetString("UpdatedTrackedEntityInUnitOfWorkNonExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating unit of work with loaded entity with identifier {0}. Scope {1}.
        /// </summary>
        internal static string UpdatingUnitOfWork {
            get {
                return ResourceManager.GetString("UpdatingUnitOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be negative..
        /// </summary>
        internal static string ValueMustNotBeNegative {
            get {
                return ResourceManager.GetString("ValueMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing metadata to entity with identifier {0}. Concurrency-token: {1}. Revision: {2}. Scope: {3}.
        /// </summary>
        internal static string WritingMetadataToEntity {
            get {
                return ResourceManager.GetString("WritingMetadataToEntity", resourceCulture);
            }
        }
    }
}
