name: Test master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
        SOLUTION: ${{ matrix.solution }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        solution: [Utils Storage Modularity Messaging Domain AspNetCore AspNetCore.Components]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src\${SOLUTION}\AI4E.$SOLUTION.sln
    - name: Build
      run: dotnet build src\${SOLUTION}\AI4E.${SOLUTION}.sln --configuration Release --no-restore
    - name: Test    
      run: dotnet test src\${SOLUTION}\AI4E.${SOLUTION}.sln --no-restore --verbosity normal
