name: Test Domain Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src\Domain\AI4E.Domain.sln
    - name: Build
      run: dotnet build src\Domain\AI4E.Domain.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src\Domain\AI4E.Domain.sln --no-restore --verbosity normal